#+TITLE: September 2023
#+SUBTITLE: 
#+DATE: [2023-09-15 vr]
#+AUTHOR: shrirambo
#+DESCRIPTION: September is 9th month of the year. Yet Sept means 7. Weird.
#+KEYWORDS:  microblog, september, 2023
#+OPTIONS: tex:t toc:nil
------


* 🍄 Idempotence
#+DATE: [2023-09-16 za 08:51]
#+TAGS: api, serverside, til,
Today I learned the concept of Idempotency, a property of set of mathematical operations that yields the same output as when applied first time. For example, consider the operation of multiplication by zero. No matter how many times you multiply a number by zero, the result is same as the first time you multiplied it. This property is useful when designing APIs for which the operations are expected to carry out only once irrespective of how many times requested. This allows carrying out heavy computations only once or modifying data only once even if multiple requests are made with same sets of parameters.

* 💲 Million dollar idea
#+DATE: [2023-09-15 vr 19:52]
#+TAGS: microblogging, idea, emacs, orgmode
I had a world class Idea today, to create my own microblog, that no one will ever read. Made with Emacs Orgmode and published as a static page. Please give me a million dollars :)

